export const LOGIN_ACTION_SUCCESS = "LOGIN_ACTION_SUCCESS"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"




export const ALERT_SUCCESS = "ALERT_SUCCESS"
export const ALERT_ERROR = "ALERT_ERROR"
export const ALERT_CLEAR = "ALERT_CLEAR"